import "./globals.css"; // ✅ Importing Tailwind
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Analytics Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
  <head>
    <link rel="icon" href="/dfvc.svg  " />
    <title>Analytics Dashboard</title>
    <meta name="description" content="Generated by create next app" />
  </head>
  <body className={`${geistSans.variable} ${geistMono.variable}`}>
    {children}
  </body>
</html>

  );
}
